# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QzJYpNzQVLEyHnEJGOa7eZl8AxriYuX0
"""

x= input('Enter a Number = ')
y= input('Enter a another Number')

print('x data type is ', type(x))
print('y data type is', type(y) ,'\n')

X= int(x)
Y= int(y)

print('x data type is ', type(X))
print('y data type is', type(Y),'\n')

print('Sum =', X+Y)
print('Sub =', X-Y)
print('Mul =', X*Y)
print('Div =', X/Y)
print('Mod =', X%Y)
print('Power =', X**Y)

a= int(input('Enter a input '))
b= int(input('Enter a input '))

print('a==b =', a==b)
print('a!=b =', a!=b)
print('a>b =', a>b)
print('a<b =', a<b)
print('a>=b =', a>=b)
print('a<=b =', a<=b)

A=[1,2,3,4,5,6,7,89]
for i in A:
 print(i ,end=' ')

X= 'State university of Bangladesh'
for i in X:
   print(i, end='')

N= int(input('Enter a Number = '))
sum=0
for i in range(1,N+1):
    sum= sum+i
    print(i, end=' ')

print('\nTotal Sum=', sum)

Number= int(input('Enter a Number = '))

if Number>1:
 for i in range (2,Number):
  if Number % i == 0:
    print(Number, 'is not a prime number')
    break
  else:
    print(Number, 'is a prime number')
    break

else:
 print(Number, 'is not a prime number')

A=[1, 4,3,43, 544,54 ,565 ,545, 565,4,44]

larg = A[0]

for i in A:
  if i > larg:
    larg = i

print('Largest Number =', larg)

num=0
while num<10:
  num= num+1
  if num%2 !=0:
    print(num, 'THIS IS ODD')
  else:
    print(num, 'THIS IS EVEN')

Array=[1,32,34,43,43,435,67,564,564,54,34,345,77,]
larg = Array[0]
for i in Array:
  if i > larg:
    larg = i

print('Largest Number =', larg)

N= int(input('Enter a Number = '))
revarse= 0
while N>0 :
   x= N%10
   revarse = revarse*10 + x
   N = N//10


print ('Revarse Number is ', revarse)

num=10
for i in range(1, num+1):
  if i%2 == 0:
    print(i, 'THIS IS EVEN')
  else:
    print(i, 'THIS IS ODD')

import random
print(random.random())

import random
A=['a', 'b', 'c', 'd']
print(random.choice(A))
random.shuffle(A)
print(A)

import math
print(math.sin(90))



